[project]
name = "mighty-security"
version = "0.1.0"
description = "A tooling for security analysis of MCP servers"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "modal>=1.1.1",
]
