[project]
name = "mighty-security"
version = "0.1.0"
description = "A tooling for security analysis of MCP servers"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cerebras-cloud-sdk>=1.46.0",
    "modal>=1.1.1",
]

[tool.uv.workspace]
members = [
    "flask-mcp-api",
]
